#############################################################################
# Makefile for building: textureatlasmaker.app/Contents/MacOS/textureatlasmaker
# Generated by qmake (2.01a) (Qt 4.5.1) on: Mon Jun 22 17:11:20 2009
# Project:  atlasmaker.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx CONFIG+=release -o Makefile atlasmaker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -Os -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -Os -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.5/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -Itinyxml -Isrc -Iobj -Iobj -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework Carbon -framework AppKit -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		tinyxml/tinyxml.cpp \
		tinyxml/tinyxmlparser.cpp \
		tinyxml/tinyxmlerror.cpp \
		tinyxml/tinystr.cpp \
		src/texturemodel.cpp \
		src/texturelistwidget.cpp \
		src/workarea.cpp obj/moc_mainwindow.cpp \
		obj/moc_texturemodel.cpp \
		obj/moc_workarea.cpp \
		obj/res/qrc_texture.cpp
OBJECTS       = obj/main.o \
		obj/mainwindow.o \
		obj/tinyxml.o \
		obj/tinyxmlparser.o \
		obj/tinyxmlerror.o \
		obj/tinystr.o \
		obj/texturemodel.o \
		obj/texturelistwidget.o \
		obj/workarea.o \
		obj/moc_mainwindow.o \
		obj/moc_texturemodel.o \
		obj/moc_workarea.o \
		obj/qrc_texture.o
DIST          = /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/release.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		atlasmaker.pro
QMAKE_TARGET  = textureatlasmaker
DESTDIR       = 
TARGET        = textureatlasmaker.app/Contents/MacOS/textureatlasmaker

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-Os \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile textureatlasmaker.app/Contents/PkgInfo textureatlasmaker.app/Contents/Resources/empty.lproj textureatlasmaker.app/Contents/Info.plist $(TARGET)

$(TARGET): obj/ui_mainform.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) textureatlasmaker.app/Contents/MacOS/ || $(MKDIR) textureatlasmaker.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: atlasmaker.pro  /usr/local/Qt4.5/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/release.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx CONFIG+=release -o Makefile atlasmaker.pro
/usr/local/Qt4.5/mkspecs/common/unix.conf:
/usr/local/Qt4.5/mkspecs/common/mac.conf:
/usr/local/Qt4.5/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.5/mkspecs/qconfig.pri:
/usr/local/Qt4.5/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.5/mkspecs/features/qt_config.prf:
/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.5/mkspecs/features/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/release.prf:
/usr/local/Qt4.5/mkspecs/features/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.5/mkspecs/features/warn_on.prf:
/usr/local/Qt4.5/mkspecs/features/qt.prf:
/usr/local/Qt4.5/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.5/mkspecs/features/moc.prf:
/usr/local/Qt4.5/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.5/mkspecs/features/resources.prf:
/usr/local/Qt4.5/mkspecs/features/uic.prf:
/usr/local/Qt4.5/mkspecs/features/yacc.prf:
/usr/local/Qt4.5/mkspecs/features/lex.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx CONFIG+=release -o Makefile atlasmaker.pro

textureatlasmaker.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) textureatlasmaker.app/Contents || $(MKDIR) textureatlasmaker.app/Contents 
	@$(DEL_FILE) textureatlasmaker.app/Contents/PkgInfo
	@echo "APPL????" >textureatlasmaker.app/Contents/PkgInfo
textureatlasmaker.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) textureatlasmaker.app/Contents/Resources || $(MKDIR) textureatlasmaker.app/Contents/Resources 
	@touch textureatlasmaker.app/Contents/Resources/empty.lproj
	
textureatlasmaker.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) textureatlasmaker.app/Contents || $(MKDIR) textureatlasmaker.app/Contents 
	@$(DEL_FILE) textureatlasmaker.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,textureatlasmaker,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.5/mkspecs/macx-g++/Info.plist.app >textureatlasmaker.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) obj/textureatlasmaker1.0.0 || $(MKDIR) obj/textureatlasmaker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h tinyxml/tinyxml.h tinyxml/tinystr.h src/texturemodel.h src/texturelistwidget.h src/workarea.h src/common.h obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/texture.qrc obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp tinyxml/tinyxml.cpp tinyxml/tinyxmlparser.cpp tinyxml/tinyxmlerror.cpp tinyxml/tinystr.cpp src/texturemodel.cpp src/texturelistwidget.cpp src/workarea.cpp obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/mainform.ui obj/textureatlasmaker1.0.0/ && (cd `dirname obj/textureatlasmaker1.0.0` && $(TAR) textureatlasmaker1.0.0.tar textureatlasmaker1.0.0 && $(COMPRESS) textureatlasmaker1.0.0.tar) && $(MOVE) `dirname obj/textureatlasmaker1.0.0`/textureatlasmaker1.0.0.tar.gz . && $(DEL_FILE) -r obj/textureatlasmaker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r textureatlasmaker.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: obj/moc_mainwindow.cpp obj/moc_texturemodel.cpp obj/moc_workarea.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_mainwindow.cpp obj/moc_texturemodel.cpp obj/moc_workarea.cpp
obj/moc_mainwindow.cpp: obj/ui_mainform.h \
		src/texturemodel.h \
		src/common.h \
		src/mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/mainwindow.h -o obj/moc_mainwindow.cpp

obj/moc_texturemodel.cpp: src/common.h \
		src/texturemodel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/texturemodel.h -o obj/moc_texturemodel.cpp

obj/moc_workarea.cpp: src/texturemodel.h \
		src/common.h \
		src/workarea.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ src/workarea.h -o obj/moc_workarea.cpp

compiler_rcc_make_all: obj/res/qrc_texture.cpp
compiler_rcc_clean:
	-$(DEL_FILE) obj/res/qrc_texture.cpp
obj/res/qrc_texture.cpp: src/texture.qrc
	/Developer/Tools/Qt/rcc -name texture src/texture.qrc -o obj/res/qrc_texture.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: obj/ui_mainform.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_mainform.h
obj/ui_mainform.h: src/mainform.ui
	/Developer/Tools/Qt/uic src/mainform.ui -o obj/ui_mainform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp src/mainwindow.h \
		obj/ui_mainform.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		obj/ui_mainform.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/tinyxml.o: tinyxml/tinyxml.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinyxml.o tinyxml/tinyxml.cpp

obj/tinyxmlparser.o: tinyxml/tinyxmlparser.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinyxmlparser.o tinyxml/tinyxmlparser.cpp

obj/tinyxmlerror.o: tinyxml/tinyxmlerror.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinyxmlerror.o tinyxml/tinyxmlerror.cpp

obj/tinystr.o: tinyxml/tinystr.cpp tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinystr.o tinyxml/tinystr.cpp

obj/texturemodel.o: src/texturemodel.cpp src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/texturemodel.o src/texturemodel.cpp

obj/texturelistwidget.o: src/texturelistwidget.cpp src/texturelistwidget.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/texturelistwidget.o src/texturelistwidget.cpp

obj/workarea.o: src/workarea.cpp src/workarea.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/workarea.o src/workarea.cpp

obj/moc_mainwindow.o: obj/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o obj/moc_mainwindow.cpp

obj/moc_texturemodel.o: obj/moc_texturemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_texturemodel.o obj/moc_texturemodel.cpp

obj/moc_workarea.o: obj/moc_workarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_workarea.o obj/moc_workarea.cpp

obj/qrc_texture.o: obj/res/qrc_texture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_texture.o obj/res/qrc_texture.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

