#############################################################################
# Makefile for building: textureatlasmaker
# Generated by qmake (2.01a) (Qt 4.5.1) on: ?? ???? 16 01:32:29 2009
# Project:  atlasmaker.pro
# Template: app
# Command: /opt/qtsdk-2009.02/qt/bin/qmake -spec /opt/qtsdk-2009.02/qt/mkspecs/linux-g++ -unix -o Makefile atlasmaker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2009.02/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2009.02/qt/include/QtCore -I/opt/qtsdk-2009.02/qt/include/QtGui -I/opt/qtsdk-2009.02/qt/include -Itinyxml -Isrc -Iobj -Iobj
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qtsdk-2009.02/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2009.02/qt/lib -lQtGui -L/opt/qtsdk-2009.02/qt/lib -L/usr/X11R6/lib -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2009.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		tinyxml/tinyxml.cpp \
		tinyxml/tinyxmlparser.cpp \
		tinyxml/tinyxmlerror.cpp \
		tinyxml/tinystr.cpp \
		src/texturemodel.cpp \
		src/texturelistwidget.cpp \
		src/workarea.cpp obj/moc_mainwindow.cpp \
		obj/moc_texturemodel.cpp \
		obj/moc_workarea.cpp \
		obj/res/qrc_texture.cpp
OBJECTS       = obj/main.o \
		obj/mainwindow.o \
		obj/tinyxml.o \
		obj/tinyxmlparser.o \
		obj/tinyxmlerror.o \
		obj/tinystr.o \
		obj/texturemodel.o \
		obj/texturelistwidget.o \
		obj/workarea.o \
		obj/moc_mainwindow.o \
		obj/moc_texturemodel.o \
		obj/moc_workarea.o \
		obj/qrc_texture.o
DIST          = /opt/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		atlasmaker.pro
QMAKE_TARGET  = textureatlasmaker
DESTDIR       = 
TARGET        = textureatlasmaker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): obj/ui_mainform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: atlasmaker.pro  /opt/qtsdk-2009.02/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/release.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2009.02/qt/lib/libQtGui.prl \
		/opt/qtsdk-2009.02/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2009.02/qt/mkspecs/linux-g++ -unix -o Makefile atlasmaker.pro
/opt/qtsdk-2009.02/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2009.02/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2009.02/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2009.02/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/release.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2009.02/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2009.02/qt/lib/libQtGui.prl:
/opt/qtsdk-2009.02/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2009.02/qt/mkspecs/linux-g++ -unix -o Makefile atlasmaker.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/textureatlasmaker1.0.0 || $(MKDIR) obj/textureatlasmaker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h tinyxml/tinyxml.h tinyxml/tinystr.h src/texturemodel.h src/texturelistwidget.h src/workarea.h src/common.h obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/texture.qrc obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp tinyxml/tinyxml.cpp tinyxml/tinyxmlparser.cpp tinyxml/tinyxmlerror.cpp tinyxml/tinystr.cpp src/texturemodel.cpp src/texturelistwidget.cpp src/workarea.cpp obj/textureatlasmaker1.0.0/ && $(COPY_FILE) --parents src/mainform.ui obj/textureatlasmaker1.0.0/ && (cd `dirname obj/textureatlasmaker1.0.0` && $(TAR) textureatlasmaker1.0.0.tar textureatlasmaker1.0.0 && $(COMPRESS) textureatlasmaker1.0.0.tar) && $(MOVE) `dirname obj/textureatlasmaker1.0.0`/textureatlasmaker1.0.0.tar.gz . && $(DEL_FILE) -r obj/textureatlasmaker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: obj/moc_mainwindow.cpp obj/moc_texturemodel.cpp obj/moc_workarea.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_mainwindow.cpp obj/moc_texturemodel.cpp obj/moc_workarea.cpp
obj/moc_mainwindow.cpp: obj/ui_mainform.h \
		src/texturemodel.h \
		src/common.h \
		src/mainwindow.h
	/opt/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o obj/moc_mainwindow.cpp

obj/moc_texturemodel.cpp: src/common.h \
		src/texturemodel.h
	/opt/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) src/texturemodel.h -o obj/moc_texturemodel.cpp

obj/moc_workarea.cpp: src/texturemodel.h \
		src/common.h \
		src/workarea.h
	/opt/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) src/workarea.h -o obj/moc_workarea.cpp

compiler_rcc_make_all: obj/res/qrc_texture.cpp
compiler_rcc_clean:
	-$(DEL_FILE) obj/res/qrc_texture.cpp
obj/res/qrc_texture.cpp: src/texture.qrc
	/opt/qtsdk-2009.02/qt/bin/rcc -name texture src/texture.qrc -o obj/res/qrc_texture.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: obj/ui_mainform.h
compiler_uic_clean:
	-$(DEL_FILE) obj/ui_mainform.h
obj/ui_mainform.h: src/mainform.ui
	/opt/qtsdk-2009.02/qt/bin/uic src/mainform.ui -o obj/ui_mainform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/main.o: src/main.cpp src/mainwindow.h \
		obj/ui_mainform.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		obj/ui_mainform.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/mainwindow.cpp

obj/tinyxml.o: tinyxml/tinyxml.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinyxml.o tinyxml/tinyxml.cpp

obj/tinyxmlparser.o: tinyxml/tinyxmlparser.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinyxmlparser.o tinyxml/tinyxmlparser.cpp

obj/tinyxmlerror.o: tinyxml/tinyxmlerror.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinyxmlerror.o tinyxml/tinyxmlerror.cpp

obj/tinystr.o: tinyxml/tinystr.cpp tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tinystr.o tinyxml/tinystr.cpp

obj/texturemodel.o: src/texturemodel.cpp src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/texturemodel.o src/texturemodel.cpp

obj/texturelistwidget.o: src/texturelistwidget.cpp src/texturelistwidget.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/texturelistwidget.o src/texturelistwidget.cpp

obj/workarea.o: src/workarea.cpp src/workarea.h \
		src/texturemodel.h \
		src/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/workarea.o src/workarea.cpp

obj/moc_mainwindow.o: obj/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o obj/moc_mainwindow.cpp

obj/moc_texturemodel.o: obj/moc_texturemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_texturemodel.o obj/moc_texturemodel.cpp

obj/moc_workarea.o: obj/moc_workarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_workarea.o obj/moc_workarea.cpp

obj/qrc_texture.o: obj/res/qrc_texture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_texture.o obj/res/qrc_texture.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

